import type { TreeNode } from "./types";

const q = (text: string, yes: TreeNode, no: TreeNode): TreeNode => ({
  type: "question", text, yes, no,
});
const a = (animal: string, emoji: string): TreeNode => ({
  type: "answer", animal, emoji,
});

// Tree structured to mix categories and feel surprising
export const defaultTree: TreeNode = q("Is it bigger than a cat?",

  // === BIGGER THAN A CAT ===
  q("Does it have fur or hair?",

    // Furry big animals
    q("Could you find it on a farm?",
      q("Can you ride it?",
        q("Does it say 'neigh'?",
          a("Horse", "🐴"),
          q("Does it have a hump?",
            q("Does it have two humps?",
              a("Bactrian Camel", "🐫"),
              a("Dromedary Camel", "🐪"),
            ),
            a("Donkey", "🫏"),
          ),
        ),
        q("Does it say 'moo'?",
          a("Cow", "🐄"),
          q("Does it roll in mud?",
            a("Pig", "🐷"),
            q("Does it give us wool?",
              a("Sheep", "🐑"),
              q("Does it climb on rocks?",
                a("Goat", "🐐"),
                q("Does it guard the farm?",
                  a("Farm Dog", "🐕"),
                  q("Does it chase mice in the barn?",
                    a("Farm Cat", "🐈"),
                    a("Alpaca", "🦙"),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      q("Does it eat other animals?",
        q("Is it a type of cat?",
          q("Does it have stripes?",
            a("Tiger", "🐯"),
            q("Does it have a mane?",
              a("Lion", "🦁"),
              q("Is it the fastest land animal?",
                a("Cheetah", "🐆"),
                q("Does it have spots?",
                  a("Leopard", "🐆"),
                  q("Is it all black?",
                    a("Panther", "🐆"),
                    q("Does it live in snowy mountains?",
                      a("Snow Leopard", "🐆"),
                      a("Cougar", "🐆"),
                    ),
                  ),
                ),
              ),
            ),
          ),
          q("Does it live in very cold places?",
            q("Is it white?",
              a("Polar Bear", "🐻‍❄️"),
              q("Does it hunt in packs?",
                a("Wolf", "🐺"),
                a("Arctic Fox", "🦊"),
              ),
            ),
            q("Does it laugh?",
              a("Hyena", "🐺"),
              q("Does it fish in rivers?",
                q("Is it brown?",
                  a("Grizzly Bear", "🐻"),
                  a("Black Bear", "🐻"),
                ),
                q("Does it have red-brown fur and a bushy tail?",
                  a("Red Fox", "🦊"),
                  q("Does it look like a big wild dog?",
                    a("African Wild Dog", "🐕"),
                    q("Does it have striped fur and long snout?",
                      a("Tasmanian Devil", "😈"),
                      a("Wolverine", "🦡"),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
        q("Does it live in Africa?",
          q("Does it have a very long neck?",
            a("Giraffe", "🦒"),
            q("Does it have a horn on its nose?",
              q("Does it have two horns?",
                a("White Rhinoceros", "🦏"),
                a("Black Rhinoceros", "🦏"),
              ),
              q("Does it have stripes like a horse?",
                a("Zebra", "🦓"),
                q("Does it have horns and a big body?",
                  a("Buffalo", "🐃"),
                  q("Is it our closest relative?",
                    a("Gorilla", "🦍"),
                    q("Does it have a colorful face?",
                      a("Mandrill", "🐒"),
                      q("Is it a very large antelope?",
                        a("Eland", "🦌"),
                        a("Wildebeest", "🐃"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
          q("Does it have antlers?",
            q("Does it pull Santa's sleigh?",
              a("Reindeer", "🦌"),
              q("Is it very big with flat antlers?",
                a("Moose", "🫎"),
                q("Does it have spotted fur when young?",
                  a("Fallow Deer", "🦌"),
                  a("Red Deer", "🦌"),
                ),
              ),
            ),
            q("Does it eat bamboo?",
              a("Panda", "🐼"),
              q("Does it have a big flat tail?",
                a("Beaver", "🦫"),
                q("Does it have very thick fur?",
                  a("Bison", "🦬"),
                  q("Does it hop and carry babies in a pouch?",
                    q("Is it very big and muscular?",
                      a("Red Kangaroo", "🦘"),
                      a("Wallaby", "🦘"),
                    ),
                    q("Does it live in trees and is very slow?",
                      a("Sloth", "🦥"),
                      q("Does it have a long curly tail?",
                        a("Llama", "🦙"),
                        q("Does it like rolling in the water?",
                          a("Capybara", "🐹"),
                          q("Does it have a strong pouch and fuzzy ears?",
                            a("Wombat", "🐻"),
                            q("Does it have a very long snout?",
                              a("Anteater", "🐾"),
                              a("Tapir", "🐾"),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),

    // Big but no fur
    q("Does it live in water?",
      q("Is it a mammal?",
        q("Is it the biggest animal in the world?",
          a("Blue Whale", "🐋"),
          q("Does it do tricks and is very smart?",
            q("Does it have a long nose?",
              a("Bottlenose Dolphin", "🐬"),
              a("Beluga Whale", "🐳"),
            ),
            q("Is it black and white?",
              a("Orca", "🐋"),
              q("Does it have a horn like a unicorn?",
                a("Narwhal", "🦄"),
                q("Does it have whiskers and flippers?",
                  q("Is it very large and gentle?",
                    a("Manatee", "🦭"),
                    q("Does it bark like a dog?",
                      a("Sea Lion", "🦭"),
                      a("Seal", "🦭"),
                    ),
                  ),
                  q("Does it have a blowhole on top?",
                    a("Humpback Whale", "🐋"),
                    a("Sperm Whale", "🐳"),
                  ),
                ),
              ),
            ),
          ),
        ),
        q("Is it dangerous?",
          q("Does it have very sharp teeth?",
            q("Is it the biggest and scariest?",
              a("Great White Shark", "🦈"),
              q("Does it have a hammer-shaped head?",
                a("Hammerhead Shark", "🦈"),
                a("Bull Shark", "🦈"),
              ),
            ),
            q("Does it have tentacles?",
              a("Giant Squid", "🦑"),
              q("Does it have a flat body with a tail?",
                a("Stingray", "🐠"),
                a("Manta Ray", "🐠"),
              ),
            ),
          ),
          q("Does it have a shell?",
            q("Is it very, very old and slow?",
              a("Sea Turtle", "🐢"),
              a("Giant Clam", "🐚"),
            ),
            q("Does it have 8 arms?",
              a("Octopus", "🐙"),
              q("Does it have a long sword-like nose?",
                a("Swordfish", "🐟"),
                q("Is it the fastest fish in the sea?",
                  a("Marlin", "🐟"),
                  a("Tuna", "🐟"),
                ),
              ),
            ),
          ),
        ),
      ),
      q("Is it a bird?",
        q("Can it fly?",
          q("Does it hunt from the sky?",
            q("Is it the symbol of America?",
              a("Bald Eagle", "🦅"),
              q("Does it hunt at night?",
                q("Is it very large?",
                  a("Great Horned Owl", "🦉"),
                  a("Barn Owl", "🦉"),
                ),
                q("Is it very fast when diving?",
                  a("Peregrine Falcon", "🦅"),
                  a("Red-tailed Hawk", "🦅"),
                ),
              ),
            ),
            q("Is it pink?",
              a("Flamingo", "🦩"),
              q("Does it have beautiful tail feathers?",
                a("Peacock", "🦚"),
                q("Is it white and swims in lakes?",
                  a("Swan", "🦢"),
                  q("Does it deliver babies in stories?",
                    a("Stork", "🪿"),
                    q("Does it have a very large beak pouch?",
                      a("Pelican", "🐦"),
                      q("Does it have colorful feathers and a big beak?",
                        a("Toucan", "🐦"),
                        a("Crane", "🪿"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
          q("Does it run very fast?",
            a("Ostrich", "🐦"),
            q("Does it live where it's very cold?",
              q("Is it small and cute?",
                a("Little Penguin", "🐧"),
                a("Emperor Penguin", "🐧"),
              ),
              q("Does it come from New Zealand?",
                a("Kiwi", "🐦"),
                a("Emu", "🐦"),
              ),
            ),
          ),
        ),
        q("Does it have a shell?",
          q("Does it walk sideways?",
            q("Is it very big?",
              a("King Crab", "🦀"),
              a("Crab", "🦀"),
            ),
            q("Does it have big claws?",
              a("Lobster", "🦞"),
              a("Hermit Crab", "🦀"),
            ),
          ),
          q("Does it have big jaws and sharp teeth?",
            q("Does it live near rivers?",
              q("Does it have a narrow snout?",
                a("Gharial", "🐊"),
                a("Crocodile", "🐊"),
              ),
              a("Alligator", "🐊"),
            ),
            q("Does it have a trunk?",
              q("Does it have very big ears?",
                a("African Elephant", "🐘"),
                a("Asian Elephant", "🐘"),
              ),
              q("Does it have a big mouth and loves water?",
                a("Hippo", "🦛"),
                q("Is it a very big lizard?",
                  q("Does it live on an island in Indonesia?",
                    a("Komodo Dragon", "🦎"),
                    a("Monitor Lizard", "🦎"),
                  ),
                  q("Does it have a hard bony back?",
                    a("Giant Tortoise", "🐢"),
                    q("Does it change colors?",
                      a("Giant Chameleon", "🦎"),
                      q("Does it have a frill around its neck?",
                        a("Frilled Lizard", "🦎"),
                        a("Iguana", "🦎"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),

  // === SMALLER THAN A CAT ===
  q("Does it have legs?",

    // Has legs, smaller than cat
    q("Is it someone's pet?",
      q("Does it say 'meow'?",
        a("Cat", "🐱"),
        q("Does it say 'woof'?",
          q("Is it very small and fits in a bag?",
            a("Chihuahua", "🐶"),
            a("Puppy", "🐶"),
          ),
          q("Does it run on a wheel?",
            a("Hamster", "🐹"),
            q("Does it have long floppy ears?",
              a("Rabbit", "🐰"),
              q("Does it have a shell?",
                a("Pet Turtle", "🐢"),
                q("Does it have spiny quills?",
                  a("Pet Hedgehog", "🦔"),
                  q("Does it have a very long body?",
                    a("Ferret", "🐾"),
                    q("Does it live in a cage and sing?",
                      a("Budgie", "🐦"),
                      a("Guinea Pig", "🐹"),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      q("Does it have more than 4 legs?",
        q("Does it have 8 legs?",
          q("Does it make webs?",
            q("Is it very big and hairy?",
              a("Tarantula", "🕷️"),
              q("Does it have a red mark on its belly?",
                a("Black Widow", "🕷️"),
                a("Garden Spider", "🕷️"),
              ),
            ),
            q("Does it glow under UV light?",
              a("Scorpion", "🦂"),
              q("Is it very tiny and lives in grass?",
                a("Tick", "🕷️"),
                a("Daddy Long Legs", "🕷️"),
              ),
            ),
          ),
          q("Does it have wings?",
            q("Does it make honey?",
              q("Is it big and fuzzy?",
                a("Bumblebee", "🐝"),
                a("Honeybee", "🐝"),
              ),
              q("Does it have colorful wings?",
                q("Does it come from a caterpillar?",
                  q("Is it very big?",
                    a("Monarch Butterfly", "🦋"),
                    a("Butterfly", "🦋"),
                  ),
                  a("Moth", "🦋"),
                ),
                q("Does it bite and buzz near your ear?",
                  a("Mosquito", "🦟"),
                  q("Does it glow at night?",
                    a("Firefly", "🪲"),
                    q("Does it have big eyes and a long body?",
                      a("Dragonfly", "🪰"),
                      q("Does it have a narrow waist and sting?",
                        a("Wasp", "🐝"),
                        q("Is it very annoying at picnics?",
                          a("Fly", "🪰"),
                          a("Gnat", "🪰"),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            q("Does it have a hard shell?",
              q("Is it red with black spots?",
                a("Ladybug", "🐞"),
                q("Does it have big horns?",
                  a("Stag Beetle", "🪲"),
                  q("Does it glow in the dark?",
                    a("Glowworm", "🪲"),
                    q("Does it eat wood?",
                      a("Termite", "🪲"),
                      a("Beetle", "🪲"),
                    ),
                  ),
                ),
              ),
              q("Does it jump?",
                q("Does it make chirping music?",
                  a("Cricket", "🦗"),
                  a("Grasshopper", "🦗"),
                ),
                q("Does it carry food in a line?",
                  a("Ant", "🐜"),
                  q("Does it have many, many legs?",
                    q("Is it flat?",
                      a("Centipede", "🐛"),
                      a("Millipede", "🐛"),
                    ),
                    q("Does it eat leaves and become a butterfly?",
                      a("Caterpillar", "🐛"),
                      q("Does it roll into a ball?",
                        a("Pill Bug", "🐛"),
                        a("Earwig", "🐛"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
        // 4 legs or 2 legs, wild, small
        q("Can it fly?",
          q("Can it talk or copy sounds?",
            a("Parrot", "🦜"),
            q("Is it very tiny and drinks from flowers?",
              a("Hummingbird", "🐦"),
              q("Does it sing pretty songs?",
                a("Canary", "🐦"),
                q("Is it red?",
                  a("Cardinal", "🐦"),
                  q("Does it say 'coo'?",
                    a("Pigeon", "🕊️"),
                    q("Is it blue and noisy?",
                      a("Blue Jay", "🐦"),
                      q("Does it peck on trees?",
                        a("Woodpecker", "🐦"),
                        q("Does it have a red breast?",
                          a("Robin", "🐦"),
                          q("Is it black and very smart?",
                            a("Crow", "🐦"),
                            a("Sparrow", "🐦"),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
          q("Does it live in trees?",
            q("Does it swing from branches?",
              q("Is it very small?",
                a("Marmoset", "🐒"),
                a("Monkey", "🐒"),
              ),
              q("Does it have a bushy tail?",
                q("Does it fly between trees?",
                  a("Flying Squirrel", "🐿️"),
                  a("Squirrel", "🐿️"),
                ),
                q("Does it sleep all day and eat leaves?",
                  a("Koala", "🐨"),
                  q("Does it change color?",
                    a("Chameleon", "🦎"),
                    q("Does it have a curly tail and big eyes?",
                      a("Lemur", "🐒"),
                      q("Does it have a long sticky tongue?",
                        a("Tree Frog", "🐸"),
                        a("Sugar Glider", "🐿️"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            q("Does it come out mostly at night?",
              q("Does it have a mask on its face?",
                a("Raccoon", "🦝"),
                q("Does it spray a stinky smell?",
                  a("Skunk", "🦨"),
                  q("Does it have quills or spines?",
                    a("Hedgehog", "🦔"),
                    q("Does it fly at night using sound?",
                      a("Bat", "🦇"),
                      q("Does it play dead when scared?",
                        a("Opossum", "🐁"),
                        a("Porcupine", "🦔"),
                      ),
                    ),
                  ),
                ),
              ),
              q("Does it hop?",
                q("Does it say 'ribbit'?",
                  q("Is it very colorful and poisonous?",
                    a("Poison Dart Frog", "🐸"),
                    q("Is it very big?",
                      a("Bullfrog", "🐸"),
                      a("Frog", "🐸"),
                    ),
                  ),
                  q("Does it have a bumpy skin?",
                    a("Toad", "🐸"),
                    a("Tree Kangaroo", "🦘"),
                  ),
                ),
                q("Does it have a bushy orange tail?",
                  a("Fox", "🦊"),
                  q("Is it very small?",
                    q("Does it have a very long tail?",
                      a("Rat", "🐀"),
                      a("Mouse", "🐭"),
                    ),
                    q("Does it have webbed feet and a bill?",
                      a("Platypus", "🦆"),
                      q("Does it swim and play?",
                        a("Otter", "🦦"),
                        q("Does it have a striped tail?",
                          a("Ring-tailed Cat", "🐱"),
                          q("Does it dig big tunnels?",
                            a("Badger", "🦡"),
                            q("Is it spotted and lives in grasslands?",
                              a("Meerkat", "🐾"),
                              a("Mongoose", "🐾"),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),

    // No legs
    q("Does it live in water?",
      q("Is it dangerous?",
        q("Does it sting?",
          q("Is it see-through?",
            a("Box Jellyfish", "🪼"),
            a("Jellyfish", "🪼"),
          ),
          q("Does it have very sharp teeth?",
            a("Piranha", "🐟"),
            q("Does it look like a stone on the bottom?",
              a("Stonefish", "🐟"),
              a("Lionfish", "🐟"),
            ),
          ),
        ),
        q("Is it very colorful?",
          q("Does it live near coral reefs?",
            q("Does it have stripes?",
              a("Clownfish", "🐠"),
              a("Angelfish", "🐠"),
            ),
            q("Does it have a round body?",
              a("Discus Fish", "🐠"),
              a("Tropical Fish", "🐠"),
            ),
          ),
          q("Does it have a long body?",
            q("Is it like a snake underwater?",
              a("Moray Eel", "🐍"),
              a("Electric Eel", "🐍"),
            ),
            q("Can it puff up into a ball?",
              a("Pufferfish", "🐡"),
              q("Does it look like a little horse?",
                a("Seahorse", "🐴"),
                q("Does it have lots of little legs?",
                  a("Shrimp", "🦐"),
                  q("Is it flat on the ocean floor?",
                    a("Flounder", "🐟"),
                    q("Does it have a star shape?",
                      a("Starfish", "⭐"),
                      q("Does it have a shell?",
                        q("Does it make pearls?",
                          a("Oyster", "🦪"),
                          q("Does it have a spiral shell?",
                            a("Sea Snail", "🐌"),
                            a("Mussel", "🦪"),
                          ),
                        ),
                        q("Does it have tentacles?",
                          a("Squid", "🦑"),
                          q("Does it look like a plant?",
                            a("Sea Anemone", "🪸"),
                            q("Does it have a round body with spines?",
                              a("Sea Urchin", "🪸"),
                              q("Does it look like a worm?",
                                a("Sea Cucumber", "🪸"),
                                a("Goldfish", "🐟"),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      q("Is it dangerous?",
        q("Does it have a rattle on its tail?",
          a("Rattlesnake", "🐍"),
          q("Does it have a hood around its head?",
            a("Cobra", "🐍"),
            q("Is it very long and squeezes its prey?",
              q("Is it the biggest snake in the world?",
                a("Anaconda", "🐍"),
                q("Does it have beautiful patterns?",
                  a("Boa Constrictor", "🐍"),
                  a("Python", "🐍"),
                ),
              ),
              q("Is it very small and colorful?",
                a("Coral Snake", "🐍"),
                a("Viper", "🐍"),
              ),
            ),
          ),
        ),
        q("Does it slither?",
          q("Is it harmless and common in gardens?",
            a("Garter Snake", "🐍"),
            q("Is it green?",
              a("Green Tree Snake", "🐍"),
              a("Grass Snake", "🐍"),
            ),
          ),
          q("Does it leave a slimy trail?",
            q("Does it have a shell?",
              a("Snail", "🐌"),
              a("Slug", "🐌"),
            ),
            a("Worm", "🪱"),
          ),
        ),
      ),
    ),
  ),
);
